production:
  adapter: postgresql
  encoding: unicode
  database: fha2_production
  pool: 5
  username: vagrant
  password: vagrant
        
development:
  adapter: postgresql
  encoding: unicode
  database: fha2_development
  pool: 5
  username: vagrant
  password: vagrant
      
test: &test
  adapter: postgresql
  encoding: unicode
  database: fha2_test
  pool: 5
  username: vagrant
  password: vagrant

cucumber:
  <<: *test
