production:
  adapter: postgresql
  encoding: unicode
  database: fha2_production
  pool: 5
  username: postgres
  password:
        
development:
  adapter: postgresql
  encoding: unicode
  database: fha2_development
  pool: 5
  username: postgres
  password:
      
test: &test
  adapter: postgresql
  encoding: unicode
  database: fha2_test
  pool: 5
  username: postgres
  password:

cucumber:
  <<: *test
